using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml;
public partial class Auth_tripchart : System.Web.UI.Page
{
    sbLoaderNdPopup _popup = new sbLoaderNdPopup();
    Int32 totalSeats;
    decimal totalFare;
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["p_tripcode"].ToString() != null && Session["p_tripcode"].ToString() != "")
        {
            loadxml();
            loaddata(Session["p_tripcode"].ToString());
        }

    }

    private void Errormsg(string msg)
    {
        string popup = _popup.modalPopupSmall("D", "Please Check", msg, "Close");
        Response.Write(popup);
    }

    private void loaddata(string tripcode)
    {
        try
        {
            wsClass obj = new wsClass();
            DataTable dt = obj.gettrip_details(tripcode);
            if (dt.Rows.Count > 0)
            {
                if (dt.Rows[0]["generated_by"].ToString() == "")
                {  }
                else
                { lblbkngby.Text = "Generated By " + dt.Rows[0]["generated_by"].ToString(); }
                lblservice.Text = dt.Rows[0]["service_code"].ToString()+"/"+ dt.Rows[0]["servicetype_name"].ToString();
                lbljourneytDate.Text = dt.Rows[0]["j_date"].ToString();
                lbldeparturetime.Text = dt.Rows[0]["dept_time"].ToString();
                lblsource.Text = dt.Rows[0]["fstation_name"].ToString();
                lbldestination.Text = dt.Rows[0]["tstation_name"].ToString();
                lbldepot.Text = dt.Rows[0]["depo_name"].ToString();
                lblbusno.Text = string.IsNullOrEmpty(dt.Rows[0]["bus_code"].ToString()) ? "N/A" : dt.Rows[0]["bus_code"].ToString();
                //lblConductor.Text = string.IsNullOrEmpty(dt.Rows[0]["cond_code"].ToString()) ? "N/A" : dt.Rows[0]["cond_code"].ToString();
                // lbldriver.Text = string.IsNullOrEmpty(dt.Rows[0]["driver_code"].ToString()) ? "N/A" : dt.Rows[0]["driver_code"].ToString();
                lblConductor.Text = string.IsNullOrEmpty(dt.Rows[0]["conductor_name"].ToString()) ? "N/A" : dt.Rows[0]["conductor_name"].ToString();
                lbldriver.Text = string.IsNullOrEmpty(dt.Rows[0]["driver_name"].ToString()) ? "N/A" : dt.Rows[0]["driver_name"].ToString();


                DataTable dtt = obj.gettrip_psngr_details(tripcode);
                //lblroute.Text= dt.Rows[0][""].ToString();
                int i = 0;
                foreach (DataRow drow in dtt.Rows)
                {
                    System.Web.UI.HtmlControls.HtmlTableRow r = new System.Web.UI.HtmlControls.HtmlTableRow();
                    tbl.Controls.Add(r);

                    System.Web.UI.WebControls.Label lblSEAT_NO = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblTICKET_NO = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblTRAVELLER_NAME = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblgender = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblage = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblboardingstation = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblfare = new System.Web.UI.WebControls.Label();
                    System.Web.UI.WebControls.Label lblbookingtype = new System.Web.UI.WebControls.Label();


                    System.Web.UI.HtmlControls.HtmlTableCell c1 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c2 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c3 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c4 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c5 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c6 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c7 = new System.Web.UI.HtmlControls.HtmlTableCell();
                    System.Web.UI.HtmlControls.HtmlTableCell c8 = new System.Web.UI.HtmlControls.HtmlTableCell();

                    r.Controls.Add(c1);
                    r.Controls.Add(c2);
                    r.Controls.Add(c3);
                    r.Controls.Add(c4);
                    r.Controls.Add(c5);
                    r.Controls.Add(c6);
                    r.Controls.Add(c7);
                    r.Controls.Add(c8);

                    lblSEAT_NO.Text = dtt.Rows[i]["seat_no"].ToString();
                    lblTICKET_NO.Text = dtt.Rows[i]["ticketno"].ToString();
                    lblTRAVELLER_NAME.Text = dtt.Rows[i]["traveller_name"].ToString();
                    lblgender.Text = dtt.Rows[i]["traveller_gender"].ToString();
                    lblage.Text = dtt.Rows[i]["traveller_age"].ToString();
                    lblboardingstation.Text = dtt.Rows[i]["boarding_station"].ToString();
                    lblfare.Text = dtt.Rows[i]["amount_total"].ToString() + " ₹";
                    lblbookingtype.Text = dtt.Rows[i]["bookingmode"].ToString();


                    c1.Controls.Add(lblSEAT_NO);
                    c2.Controls.Add(lblTICKET_NO);
                    c3.Controls.Add(lblTRAVELLER_NAME);
                    c4.Controls.Add(lblgender);
                    c5.Controls.Add(lblage);
                    c6.Controls.Add(lblboardingstation);
                    c7.Controls.Add(lblfare);
                    c8.Controls.Add(lblbookingtype);


                    //totalSeats += Convert.ToInt32(dt.Rows[i]["totalseat_booked"].ToString());
                    totalFare += Convert.ToDecimal(dtt.Rows[i]["amount_total"].ToString());


                    i = i + 1;
                }
                lblTotalFare.Text = totalFare.ToString();
                lblTotalSeats.Text = dtt.Rows.Count.ToString();
            }
            else
            {
                //  Errormsg("Something Went Wrong");
            }
        }
        catch (Exception ex)
        {
            //Errormsg("Something Went Wrong");
        }

    }

    private void loadxml()
    {
        XmlDocument doc = new XmlDocument();
        doc.Load(Server.MapPath("../CommonData.xml"));
        XmlNodeList deptname = doc.GetElementsByTagName("dept_Name_en");
        lblDepartmentName.Text = deptname.Item(0).InnerXml;
    }
}